services:
  mysql:
    image: mysql:8.0
    container_name: mysql-keycloak
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"   # Keycloak accessible sur http://localhost:8081
    depends_on:
      - mysql
    networks:
      - keycloak-net

volumes:
  mysql_data:

networks:
  keycloak-net:
    driver: bridge
